name: Generate GitHub Metrics Pro

on:
  schedule:
    - cron: "0 */12 * * *" # Atualiza a cada 12h
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          user: Th1erryx
          template: classic
          base: header, activity, community, repositories
          config_timezone: America/Fortaleza

          # Linguagens
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          # Commits / contribuições
          plugin_lines: yes

          # Achievements PRO
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact

          # Followers / stars
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_stargazers: yes

          # Atividade semanal (gráfico PRO)
          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_activity_days: 14
          plugin_activity_filter: all

          # Arquivo final
          filename: github-metrics.svg
