name: Generate GitHub Metrics (Pro)

on:
  schedule:
    - cron: "0 */12 * * *"   # a cada 12 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Generate metrics image
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Th1erryx
          template: classic
          base: header, activity, community, repositories
          config_timezone: America/Fortaleza
          # plugins
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 10
          plugin_lines: yes
          plugin_achievements: yes
          plugin_followup: yes
          plugin_stargazers: yes
          plugin_activity: yes
          filename: github-metrics.svg

      - name: Commit generated metrics image
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update generated github-metrics.svg"
          add: github-metrics.svg
          author_name: GitHub Actions
          author_email: actions@github.com
